---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-application
spec:
  selector:
    matchLabels:
      app: logstash-application
  template:
    metadata:
      labels:
        app: logstash-application
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.6.1
        name: logstash-application
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        - name: logstash-api
          containerPort: 9600
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 2Gi
            cpu: "200m"
          requests:
            memory: 2Gi
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 240
        livenessProbe:
          httpGet:
            path: /
            port: 9600
          initialDelaySeconds: 300
          periodSeconds: 3
      volumes:
      - name: pipeline
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-application
  labels:
    app: logstash-application
spec:
  type: LoadBalancer
  selector:
    app: logstash-application
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP